### ISSUE TITLE
Cannot edit event time in v.8.6.5

### ISSUE THREAD

**Issue by Sarah2022A** [olivierfriard/BORIS#527]
**Can't edit time of events**

**To Reproduce**
Right click on event
Select "edit selected event(s)" in drop down menu
Editing window opens
Change time of event using arrow keys or by typing new value. 
Press OK

Outcome: editing window flickers but does not close. Event time does not change. Only option to close window is to cancel out of it. 
It is possible to edit the event comment and subject, just not the time stamp. 

**Expected behavior**
I wanted to change the timestamp of the selected event. 

**Desktop (please complete the following information):**
 - OS: [windows 10, 10.0.22000]
 - BORIS Version 8.6.5

Also! In this version of BORIS, if you go to the help button and select the "about" option from the drop down menu, it reports an error message ("an error has occurred" (which does contain the "about" information and can be cancelled out of just fine by selecting "ignore and try to continue"). Selecting "check for updates and new" from the same drop down menu, provides the "about" information.

**Comment by olivierfriard** [comment]
Hi,
thank you for reporting this.
The issue should be fixed in the v. 8.6.8 just released.
Can you confirm that?

**Comment by Sarah2022A** [comment]
Hi Olivier, the errors are almost identical in v 8.6.8, including the help/about issue.

**Comment by olivierfriard** [comment]
Hi Sarah,
are you sure you are using the v. 8.6.8 ?
I tested the event time editing function and the about page and I do not obtain any error.

**Comment by Sarah2022A** [comment]
You are right, I did accidentally open the old version. Now I have tried it on v. 8. 6. 8 and no, it still does not work for me. 

To Reproduce.
Right click on event.
Select "edit selected event(s)" in drop down menu.
Editing window opens.
(This time I did not even try to make a change, just opened editing window then attempted to close it. Attempting to edit produces the same result). 
Press OK.

Outcome: Error message (image attached). 
![Screenshot 2022-09-06 112850](https://user-images.githubusercontent.com/57016893/188520604-b0837a2f-74db-4b14-b260-93a6ba92cd0e.jpg)


Also, the "help>check for updates and news" and "about" pathways now work fine.

**Comment by Sarah2022A** [comment]
Update - I deleted the error log and restarted computer twice. The first time did not produce any change, the second time I can now edit events in v 8.6.8 no problem. Mysterious computer gods, I bow to you. Thanks for your great work Olivier

**Comment by olivierfriard** [comment]
Also if you can not reproduce the issue for the moment this piece of code should be improved.
Can you send me your project file and the detailed procedure that gave you the issue?
